import { JobOppening } from "../@types/job-oppening.types"

export const jobsList: JobOppening[] = [
  {
    id: 1,
    department: "sorteio",
    title: "chefe adjunto de sorteio",
    description: "",
    requirements: [
      "Mínimo 3 anos de experiência na área",
      "Entender, interpretar normas ISO",
      "Tratamento e gestão de NC (Não Conformidade",
      "Noções de Controles Internos.",
    ],
    responsabilities: [],
    createdAt: new Date("2025-05-29"),
  },

  {
    id: 2,
    department: "transporte",
    title: "motorista",
    description: "",
    requirements: [
      "Viver no centro da cidade",
      "Carta de condução válida",
      "Experiência mínima de 2 anos",
      "Conhecimento básico de mecânica automotiva",
    ],
    responsabilities: [],
    createdAt: new Date("2025-05-02"),
  },
]

export const resellersOppenings: JobOppening[] = [
  {
    id: 1,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "hoji-ya-henda",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 2,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "cassenda",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 3,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "prenda",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 4,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "rocha-pinto",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 5,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "neves-bendinha",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 6,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "cassequel",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 7,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "catambor",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 8,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "martires",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 9,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "benfica",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 10,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "ngola-kiluanje",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 11,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "11-de-novembro",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 12,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "samba",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 13,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "kikolo",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 14,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "patriota",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 15,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "morro-bento",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 16,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "dangereux",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 17,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "fubu",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 18,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "alvalade",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 19,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "kifica",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
  {
    id: 20,
    department: "parceiro",
    title: "Revendedor",
    description: "",
    requirements: [
      "Cópia do B.I",
      "2 Fotos tipo passe",
      "Comprovativo de residência",
    ],
    location: "bairro-popular",
    responsabilities: [],
    createdAt: new Date("2025-05-29T00:00:00"),
  },
]
