export const LOGO = {
  lotaria: "/logo/logo.webp",
  isj: "/logo/isj.webp",
  adultOnly: "/logo/18+.svg",
}

export const IMAGES = {
  noticia: "/banner/noticia.webp",
  banner1: "/banner/banner-1.webp",
  banner2: "/banner/banner-2.webp",
  banner3: "/banner/banner-3.webp",
  banner4: "/banner/banner-5.webp",
  trevoBg: "/banner/bg-trevo.webp",
  cardLoto: "/banner/card-loto.webp",
  recrutamento: "/banner/recrutamento.webp",
  videoThumbnail: "/como_jogar/video-thumbnail-como-jogar.webp",
  comojogar1: "/como_jogar/banners/como-jogar-1.webp",
  comojogar2: "/como_jogar/banners/como-jogar-2.webp",
  comojogar3: "/como_jogar/banners/como-jogar-3.webp",
  comojogar4: "/como_jogar/banners/como-jogar-4.webp",
  comojogar5: "/como_jogar/banners/como-jogar-5.webp",
  comojogar6: "/como_jogar/banners/como-jogar-6.webp",
  comojogar7: "/como_jogar/banners/como-jogar-7.webp",
  comojogar8: "/como_jogar/banners/como-jogar-8.webp",
  comojogar9: "/como_jogar/banners/como-jogar-9.webp",
  comojogar10: "/como_jogar/banners/como-jogar-10.webp",
}

export const ICONS = {
  phone: "/icons/phone.png",
  etica: "/icons/etica.webp",
  roleta: "/icons/roleta.webp",
  target: "/icons/target.webp",
  valores: "/icons/valores.webp",
  tiktok: "/icons/tiktok.svg",
  tiktokGray: "/icons/tiktok-gray.svg",
  facebook: "/icons/facebook.png",
  linkedin: "/icons/linkedin.png",
  instagram: "/icons/instagram.png",
  calculadora: "/icons/calculadora.webp",
  estatisticas: "/icons/estatisticas.webp",
  verticalLine: "/icons/vertical-line.png",
  verGrafico: "/icons/ver-grafico-icon.png",
  newEstatistica: "/icons/new-estatisticas.webp",
  resultados: "/icons/modelo-resultados.webp",
}
