export const jobLocations = [
  { title: "Hoji-Ya-Henda", value: "hoji-ya-henda" },
  { title: "Cassenda", value: "cassenda" },
  { title: "Prenda", value: "prenda" },
  { title: "Rocha Pinto", value: "rocha-pinto" },
  { title: "Neves Bendinha", value: "neves-bendinha" },
  { title: "Cassequel", value: "cassequel" },
  { title: "Catambor", value: "catambor" },
  { title: "Mártires", value: "martires" },
  { title: "Benfica", value: "benfica" },
  { title: "Ngola Kiluanje", value: "ngola-kiluanje" },
  { title: "11 de Novembro", value: "11-de-novembro" },
  { title: "Samba", value: "samba" },
  { title: "Kikolo", value: "kikolo" },
  { title: "Patriota", value: "patriota" },
  { title: "Morro Bento", value: "morro-bento" },
  { title: "Dangereux", value: "dangereux" },
  { title: "Fubú", value: "fubu" },
  { title: "Alvalade", value: "alvalade" },
  { title: "Kifica", value: "kifica" },
  { title: "Bairro Popular", value: "bairro-popular" },
] as const
